# Generated by Django 5.2.1 on 2025-11-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_is_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="public_id",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
