# Generated by Django 5.2.1 on 2025-12-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_bio_user_birth_date_user_city_user_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pin_code",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
