# Generated by Django 5.2.1 on 2025-11-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Уникальный код локации (например: bishkek, osh, tokmok)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, verbose_name="Название (RU)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=255, verbose_name="Название (EN)"),
                ),
                (
                    "name_ky",
                    models.CharField(max_length=255, verbose_name="Название (KY)"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Чем меньше число, тем выше в списке",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Отображать в списках выбора",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Область/регион (опционально)",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Локация",
                "verbose_name_plural": "Локации",
                "ordering": ["sort_order", "name_ru"],
            },
        ),
    ]
