# Generated by Django 5.2.1 on 2025-11-10 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0005_alter_trip_from_location_alter_trip_to_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="published_trips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
