# Generated by Django 5.2.1 on 2025-11-29 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0009_alter_trip_status"),
        ("users", "0008_user_bio_user_birth_date_user_city_user_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TripApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("accepted", "Принята"),
                            ("rejected", "Отклонена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "proposed_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="trip",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="review",
            name="car_was_clean",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="review",
            name="was_on_time",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="was_polite",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="allow_smoking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trip",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trips",
                to="users.car",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="trip",
            name="has_luggage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trip",
            name="prefer_verified_driver",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trip",
            name="with_child",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trip",
            name="with_pet",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["status", "departure_time"], name="trips_trip_status_3a870b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["passenger"], name="trips_trip_passeng_fa7179_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(fields=["driver"], name="trips_trip_driver__54be0b_idx"),
        ),
        migrations.AddField(
            model_name="tripapplication",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trip_applications",
                to="users.car",
            ),
        ),
        migrations.AddField(
            model_name="tripapplication",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tripapplication",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="trips.trip",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tripapplication",
            unique_together={("trip", "driver")},
        ),
    ]
