# Generated by Django 5.2.1 on 2025-11-29 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0010_tripapplication_alter_review_options_and_more"),
        ("users", "0008_user_bio_user_birth_date_user_city_user_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seats_count", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждено"),
                            ("rejected", "Отклонено"),
                            ("cancelled", "Отменено"),
                            ("completed", "Завершено"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("driver_comment", models.TextField(blank=True, default="")),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DriverAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активно"),
                            ("full", "Мест нет"),
                            ("completed", "Завершено"),
                            ("cancelled", "Отменено"),
                            ("expired", "Просрочено"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("from_location", models.CharField(max_length=255)),
                ("to_location", models.CharField(max_length=255)),
                ("departure_time", models.DateTimeField()),
                ("available_seats", models.PositiveIntegerField(default=4)),
                ("booked_seats", models.PositiveIntegerField(default=0)),
                (
                    "price_per_seat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_negotiable", models.BooleanField(default=False)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                ("comment", models.TextField(blank=True, default="")),
                ("allow_smoking", models.BooleanField(default=False)),
                ("allow_pets", models.BooleanField(default=False)),
                ("allow_children", models.BooleanField(default=True)),
                ("has_air_conditioning", models.BooleanField(default=True)),
                (
                    "intermediate_stops",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Промежуточные остановки через запятую",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Объявление водителя",
                "verbose_name_plural": "Объявления водителей",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="tripapplication",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="tripapplication",
            name="car",
        ),
        migrations.RemoveField(
            model_name="tripapplication",
            name="driver",
        ),
        migrations.RemoveField(
            model_name="tripapplication",
            name="trip",
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.AlterModelOptions(
            name="trip",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Заказ пассажира",
                "verbose_name_plural": "Заказы пассажиров",
            },
        ),
        migrations.RemoveIndex(
            model_name="trip",
            name="trips_trip_status_3a870b_idx",
        ),
        migrations.RemoveIndex(
            model_name="trip",
            name="trips_trip_passeng_fa7179_idx",
        ),
        migrations.RemoveIndex(
            model_name="trip",
            name="trips_trip_driver__54be0b_idx",
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="review",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="trips.trip",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="passengers_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="booking",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="trips.booking",
            ),
        ),
        migrations.AddField(
            model_name="driverannouncement",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="announcements",
                to="users.car",
            ),
        ),
        migrations.AddField(
            model_name="driverannouncement",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="announcement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="trips.driverannouncement",
            ),
        ),
        migrations.DeleteModel(
            name="TripApplication",
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("announcement", "passenger")},
        ),
    ]
