# Generated by Django 5.2.1 on 2025-11-29 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("trips", "0011_booking_driverannouncement_and_more"),
        ("users", "0008_user_bio_user_birth_date_user_city_user_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="has_luggage",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="with_pet",
        ),
        migrations.AddField(
            model_name="driverannouncement",
            name="allow_big_luggage",
            field=models.BooleanField(
                default=True, verbose_name="Большой багаж разрешён"
            ),
        ),
        migrations.AddField(
            model_name="driverannouncement",
            name="baggage_help",
            field=models.BooleanField(default=False, verbose_name="Помогу с багажом"),
        ),
        migrations.AddField(
            model_name="driverannouncement",
            name="extra_rules",
            field=models.TextField(
                blank=True, default="", verbose_name="Дополнительные условия"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="allow_big_luggage",
            field=models.BooleanField(default=False, verbose_name="Большой багаж"),
        ),
        migrations.AddField(
            model_name="trip",
            name="allow_pets",
            field=models.BooleanField(default=False, verbose_name="Можно с животными"),
        ),
        migrations.AddField(
            model_name="trip",
            name="baggage_help",
            field=models.BooleanField(
                default=False, verbose_name="Нужна помощь с багажом"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="extra_rules",
            field=models.TextField(
                blank=True, default="", verbose_name="Дополнительные условия"
            ),
        ),
        migrations.AlterField(
            model_name="driverannouncement",
            name="allow_children",
            field=models.BooleanField(default=True, verbose_name="Можно с детьми"),
        ),
        migrations.AlterField(
            model_name="driverannouncement",
            name="allow_pets",
            field=models.BooleanField(default=False, verbose_name="Можно с животными"),
        ),
        migrations.AlterField(
            model_name="driverannouncement",
            name="allow_smoking",
            field=models.BooleanField(default=False, verbose_name="Можно курить"),
        ),
        migrations.AlterField(
            model_name="driverannouncement",
            name="from_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="announcements_from",
                to="locations.location",
                verbose_name="Откуда",
            ),
        ),
        migrations.AlterField(
            model_name="driverannouncement",
            name="has_air_conditioning",
            field=models.BooleanField(default=True, verbose_name="Кондиционер"),
        ),
        migrations.AlterField(
            model_name="driverannouncement",
            name="intermediate_stops",
            field=models.JSONField(
                blank=True, default=list, help_text="Список ID промежуточных локаций"
            ),
        ),
        migrations.AlterField(
            model_name="driverannouncement",
            name="to_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="announcements_to",
                to="locations.location",
                verbose_name="Куда",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="allow_smoking",
            field=models.BooleanField(default=False, verbose_name="Можно курить"),
        ),
        migrations.AlterField(
            model_name="trip",
            name="from_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trips_from",
                to="locations.location",
                verbose_name="Откуда",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="prefer_verified_driver",
            field=models.BooleanField(
                default=False, verbose_name="Предпочитаю верифицированного водителя"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="to_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trips_to",
                to="locations.location",
                verbose_name="Куда",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="with_child",
            field=models.BooleanField(default=False, verbose_name="С ребёнком"),
        ),
        migrations.AddIndex(
            model_name="driverannouncement",
            index=models.Index(fields=["status"], name="trips_drive_status_607154_idx"),
        ),
        migrations.AddIndex(
            model_name="driverannouncement",
            index=models.Index(
                fields=["from_location", "to_location"],
                name="trips_drive_from_lo_7b4eb2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="driverannouncement",
            index=models.Index(
                fields=["departure_time"], name="trips_drive_departu_480d5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(fields=["status"], name="trips_trip_status_259ca6_idx"),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["from_location", "to_location"],
                name="trips_trip_from_lo_8e9ec3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["departure_time"], name="trips_trip_departu_ee1fdc_idx"
            ),
        ),
    ]
