# Generated by Django 5.2.1 on 2025-12-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0012_remove_trip_has_luggage_remove_trip_with_pet_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together=set(),
        ),
    ]
