# Generated by Django 5.2.1 on 2025-11-10 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_is_driver_remove_user_is_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Телефон должен быть в международном формате, только цифры и опциональный '+'",
                        regex="^\\+?\\d{10,15}$",
                    )
                ],
            ),
        ),
    ]
