# Generated by Django 5.2.1 on 2025-11-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_driver",
            field=models.BooleanField(default=False),
        ),
    ]
