# Generated by Django 5.2.1 on 2025-11-29 07:50

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_telegram_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified_driver",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified_passenger",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="license_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=users.models.user_directory_path
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="passport_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=users.models.user_directory_path
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="trips_completed_as_driver",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="trips_completed_as_passenger",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("color", models.CharField(blank=True, default="", max_length=30)),
                (
                    "car_type",
                    models.CharField(
                        choices=[
                            ("sedan", "Седан"),
                            ("suv", "Внедорожник"),
                            ("minivan", "Минивэн"),
                            ("hatchback", "Хэтчбек"),
                            ("wagon", "Универсал"),
                            ("other", "Другое"),
                        ],
                        default="sedan",
                        max_length=20,
                    ),
                ),
                ("plate_number", models.CharField(max_length=20)),
                ("passenger_seats", models.PositiveIntegerField(default=4)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="cars/")),
                ("has_air_conditioning", models.BooleanField(default=True)),
                ("has_wifi", models.BooleanField(default=False)),
                ("has_child_seat", models.BooleanField(default=False)),
                ("allows_smoking", models.BooleanField(default=False)),
                ("allows_pets", models.BooleanField(default=False)),
                ("has_luggage_space", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "registration_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="cars/documents/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Автомобиль",
                "verbose_name_plural": "Автомобили",
            },
        ),
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("driver", "Верификация водителя"),
                            ("passenger", "Верификация пассажира"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "document_1",
                    models.ImageField(blank=True, null=True, upload_to="verification/"),
                ),
                (
                    "document_2",
                    models.ImageField(blank=True, null=True, upload_to="verification/"),
                ),
                (
                    "document_3",
                    models.ImageField(blank=True, null=True, upload_to="verification/"),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("admin_comment", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на верификацию",
                "verbose_name_plural": "Заявки на верификацию",
                "ordering": ["-created_at"],
            },
        ),
    ]
