# Generated by Django 5.2.1 on 2025-11-10 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0006_alter_trip_passenger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["status", "departure_time"], name="trips_trip_status_3a870b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["passenger"], name="trips_trip_passeng_fa7179_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(fields=["driver"], name="trips_trip_driver__54be0b_idx"),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["is_active", "departure_time"],
                name="trips_trip_is_acti_ca6933_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.CheckConstraint(
                condition=models.Q(("passengers_count__gt", 0)),
                name="trip_passengers_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("price__gte", 0), ("price__isnull", True), _connector="OR"
                ),
                name="trip_price_gte_0_or_null",
            ),
        ),
    ]
