# Generated by Django 5.2.1 on 2025-11-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0008_remove_trip_trip_passengers_gt_0_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Открыта"),
                    ("taken", "Взята"),
                    ("in_progress", "В пути"),
                    ("completed", "Завершена"),
                    ("cancelled", "Отменена"),
                    ("expired", "Просрочена"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
    ]
