# Generated by Django 5.2.1 on 2025-05-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0004_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="from_location",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="trip",
            name="to_location",
            field=models.CharField(max_length=1000),
        ),
    ]
