# Generated by Django 5.2.1 on 2025-11-18 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0007_trip_trips_trip_status_3a870b_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="trip",
            name="trip_passengers_gt_0",
        ),
        migrations.RemoveConstraint(
            model_name="trip",
            name="trip_price_gte_0_or_null",
        ),
        migrations.RemoveIndex(
            model_name="trip",
            name="trips_trip_status_3a870b_idx",
        ),
        migrations.RemoveIndex(
            model_name="trip",
            name="trips_trip_passeng_fa7179_idx",
        ),
        migrations.RemoveIndex(
            model_name="trip",
            name="trips_trip_driver__54be0b_idx",
        ),
        migrations.RemoveIndex(
            model_name="trip",
            name="trips_trip_is_acti_ca6933_idx",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="route_link",
        ),
        migrations.AddField(
            model_name="trip",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="trip",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver_trips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="from_location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="trip",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passenger_trips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Открыта"),
                    ("taken", "Взята"),
                    ("in_progress", "В пути"),
                    ("completed", "Завершена"),
                    ("cancelled", "Отменена"),
                    ("expired", "Просрочена"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="to_location",
            field=models.CharField(max_length=255),
        ),
    ]
